name: demo_crypto_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  http: ^0.13.3
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^4.1.2
  provider: ^5.0.0
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
    - family: ArchitectsDaughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
    - family: Farro
      fonts:
        - asset: fonts/Farro-Regular.ttf